#include "codegen.hpp"
#include <sstream>

std::string TargetCodeGen::tac_op_name(TACOp op) {
    switch (op) {
        case TACOp::ADD:         return "ADD";
        case TACOp::SUB:         return "SUB";
        case TACOp::MUL:         return "MUL";
        case TACOp::DIV:         return "DIV";
        case TACOp::ASSIGN:      return "ASSIGN";
        case TACOp::ARRAY_LOAD:  return "ARRAY_LOAD";
        case TACOp::ARRAY_STORE: return "ARRAY_STORE";
        case TACOp::IF_EQ:       return "IF_EQ";
        case TACOp::IF_NE:       return "IF_NE";
        case TACOp::IF_LT:       return "IF_LT";
        case TACOp::IF_GT:       return "IF_GT";
        case TACOp::IF_LE:       return "IF_LE";
        case TACOp::IF_GE:       return "IF_GE";
        case TACOp::GOTO:        return "GOTO";
        case TACOp::LABEL:       return "LABEL";
        case TACOp::PARAM:       return "PARAM";
        case TACOp::CALL:        return "CALL";
        case TACOp::RETURN_OP:   return "RETURN";
        case TACOp::READ_OP:     return "READ";
        case TACOp::WRITE_OP:    return "WRITE";
        case TACOp::WRITE_STR:   return "WRITE_STR";
        case TACOp::HALT:        return "HALT";
    }
    return "???";
}

std::vector<std::string> TargetCodeGen::generate(const std::vector<TACInstr>& tac) {
    std::vector<std::string> asm_code;
    asm_code.push_back("; F-Lite Target Assembly");
    asm_code.push_back("; Generated by F-Lite Compiler");
    asm_code.push_back("");

    for (const auto& instr : tac) {
        switch (instr.op) {
            case TACOp::ADD:
                asm_code.push_back("    LOAD  R1, " + instr.arg1);
                asm_code.push_back("    LOAD  R2, " + instr.arg2);
                asm_code.push_back("    ADD   R3, R1, R2");
                asm_code.push_back("    STORE " + instr.result + ", R3");
                break;

            case TACOp::SUB:
                asm_code.push_back("    LOAD  R1, " + instr.arg1);
                asm_code.push_back("    LOAD  R2, " + instr.arg2);
                asm_code.push_back("    SUB   R3, R1, R2");
                asm_code.push_back("    STORE " + instr.result + ", R3");
                break;

            case TACOp::MUL:
                asm_code.push_back("    LOAD  R1, " + instr.arg1);
                asm_code.push_back("    LOAD  R2, " + instr.arg2);
                asm_code.push_back("    MUL   R3, R1, R2");
                asm_code.push_back("    STORE " + instr.result + ", R3");
                break;

            case TACOp::DIV:
                asm_code.push_back("    LOAD  R1, " + instr.arg1);
                asm_code.push_back("    LOAD  R2, " + instr.arg2);
                asm_code.push_back("    DIV   R3, R1, R2");
                asm_code.push_back("    STORE " + instr.result + ", R3");
                break;

            case TACOp::ASSIGN:
                asm_code.push_back("    LOAD  R1, " + instr.arg1);
                asm_code.push_back("    STORE " + instr.result + ", R1");
                break;

            case TACOp::ARRAY_LOAD:
                asm_code.push_back("    LOAD    R1, " + instr.arg2);
                asm_code.push_back("    LOADARR R2, " + instr.arg1 + ", R1");
                asm_code.push_back("    STORE   " + instr.result + ", R2");
                break;

            case TACOp::ARRAY_STORE:
                asm_code.push_back("    LOAD     R1, " + instr.arg2);
                asm_code.push_back("    LOAD     R2, " + instr.result);
                asm_code.push_back("    STOREARR " + instr.arg1 + ", R1, R2");
                break;

            case TACOp::IF_EQ:
            case TACOp::IF_NE:
            case TACOp::IF_LT:
            case TACOp::IF_GT:
            case TACOp::IF_LE:
            case TACOp::IF_GE: {
                asm_code.push_back("    LOAD  R1, " + instr.arg1);
                asm_code.push_back("    LOAD  R2, " + instr.arg2);
                asm_code.push_back("    CMP   R1, R2");
                std::string jmp;
                switch (instr.op) {
                    case TACOp::IF_EQ: jmp = "JEQ"; break;
                    case TACOp::IF_NE: jmp = "JNE"; break;
                    case TACOp::IF_LT: jmp = "JLT"; break;
                    case TACOp::IF_GT: jmp = "JGT"; break;
                    case TACOp::IF_LE: jmp = "JLE"; break;
                    case TACOp::IF_GE: jmp = "JGE"; break;
                    default: jmp = "JMP"; break;
                }
                asm_code.push_back("    " + jmp + "   " + instr.result);
                break;
            }

            case TACOp::GOTO:
                asm_code.push_back("    JMP   " + instr.result);
                break;

            case TACOp::LABEL:
                asm_code.push_back(instr.result + ":");
                break;

            case TACOp::PARAM:
                asm_code.push_back("    LOAD  R1, " + instr.result);
                asm_code.push_back("    PUSH  R1");
                break;

            case TACOp::CALL:
                asm_code.push_back("    CALL  " + instr.result);
                break;

            case TACOp::RETURN_OP:
                asm_code.push_back("    RET");
                break;

            case TACOp::READ_OP:
                asm_code.push_back("    READ  R1");
                asm_code.push_back("    STORE " + instr.result + ", R1");
                break;

            case TACOp::WRITE_OP:
                asm_code.push_back("    LOAD  R1, " + instr.result);
                asm_code.push_back("    WRITE R1");
                break;

            case TACOp::WRITE_STR:
                asm_code.push_back("    WRITES \"" + instr.result + "\"");
                break;

            case TACOp::HALT:
                asm_code.push_back("    HALT");
                break;
        }
    }

    return asm_code;
}
